Update Build_Test_Branches.yml

diff --git a/.github/workflows/Build_Test_Branches.yml b/.github/workflows/Build_Test_Branches.yml
--- a/.github/workflows/Build_Test_Branches.yml
+++ b/.github/workflows/Build_Test_Branches.yml
@@ -23,20 +23,20 @@ jobs:
         node-version: [20.x]
 
     steps:
-    - uses: actions/checkout@v3
-    - name: Use Node.js ${{ matrix.node-version }}
-      uses: actions/setup-node@v3
-      with:
-        node-version: ${{ matrix.node-version }}
-        cache: 'npm'
+      - uses: actions/checkout@v3
+      - name: Use Node.js ${{ matrix.node-version }}
+        uses: actions/setup-node@v3
+        with:
+          node-version: ${{ matrix.node-version }}
+          cache: 'npm'
         
-    - name: Check for lock file
-    - run: |
-        if [ ! -f package-lock.json ]; then
-          echo "Error: package-lock.json is missing.";
-          exit 1;
-        fi
+      - name: Check for lock file
+      - run: |
+          if [ ! -f package-lock.json ]; then
+            echo "Error: package-lock.json is missing.";
+            exit 1;
+          fi
 
-    - run: npm ci
-    - name: Build project
-    - run: npm run build --if-present
+      - run: npm ci
+      - name: Build project
+      - run: npm run build --if-present
