Update build_test_branches.yml

diff --git a/.github/workflows/build_test_branches.yml b/.github/workflows/build_test_branches.yml
--- a/.github/workflows/build_test_branches.yml
+++ b/.github/workflows/build_test_branches.yml
@@ -22,12 +22,25 @@ jobs:
 
     steps:
     - uses: actions/checkout@v3
+    
     - name: Use Node.js ${{ matrix.node-version }}
       uses: actions/setup-node@v3
       with:
         node-version: ${{ matrix.node-version }}
         cache: 'npm'
-        
-    - run: npm ci
-    - run: npm install
-    - run: npm run build --if-present
+
+    # Check if package-lock.json exists
+    - name: Check for lock file
+      run: |
+        if [ ! -f package-lock.json ]; then
+          echo "Error: package-lock.json is missing.";
+          exit 1;
+        fi
+
+    # Install dependencies using npm ci for CI/CD environments
+    - name: Install dependencies
+      run: npm ci
+
+    # Build the project if necessary
+    - name: Build project
+      run: npm run build --if-present
